// Auto-generated by scripts/collect-demos.ts — do not edit manually

export const demoImports: Record<
  string,
  () => Promise<typeof import("@registry/ui/perimeter/button.demo")>
> = {
  button: () => import("@registry/ui/perimeter/button.demo"),
};
