// Auto-generated by scripts/collect-demos.ts — do not edit manually

import type { ControlsConfig, DemoExample, DemoMeta } from "@/lib/demo-types";

export interface DemoModule {
  meta: DemoMeta;
  controls: ControlsConfig;
  Playground: React.ComponentType<Record<string, unknown>>;
  examples: DemoExample[];
}

// Each demo exports a Playground typed to its specific controls config.
// We widen via assertion so all demos share the DemoModule interface.
export const demoImports: Record<string, () => Promise<DemoModule>> = {
  "button": () => import("@registry/ui/perimeter/button.demo") as unknown as Promise<DemoModule>,
  "button-group": () => import("@registry/ui/perimeter/button-group.demo") as unknown as Promise<DemoModule>,
  "context-menu": () => import("@registry/ui/perimeter/context-menu.demo") as unknown as Promise<DemoModule>,
  "dropdown-menu": () => import("@registry/ui/perimeter/dropdown-menu.demo") as unknown as Promise<DemoModule>,
  "menubar": () => import("@registry/ui/perimeter/menubar.demo") as unknown as Promise<DemoModule>,
  "toggle": () => import("@registry/ui/perimeter/toggle.demo") as unknown as Promise<DemoModule>,
  "toggle-group": () => import("@registry/ui/perimeter/toggle-group.demo") as unknown as Promise<DemoModule>,
  "avatar": () => import("@registry/ui/perimeter/avatar.demo") as unknown as Promise<DemoModule>,
  "badge": () => import("@registry/ui/perimeter/badge.demo") as unknown as Promise<DemoModule>,
  "card": () => import("@registry/ui/perimeter/card.demo") as unknown as Promise<DemoModule>,
  "carousel": () => import("@registry/ui/perimeter/carousel.demo") as unknown as Promise<DemoModule>,
  "chart": () => import("@registry/ui/perimeter/chart.demo") as unknown as Promise<DemoModule>,
  "empty": () => import("@registry/ui/perimeter/empty.demo") as unknown as Promise<DemoModule>,
  "progress": () => import("@registry/ui/perimeter/progress.demo") as unknown as Promise<DemoModule>,
  "skeleton": () => import("@registry/ui/perimeter/skeleton.demo") as unknown as Promise<DemoModule>,
  "table": () => import("@registry/ui/perimeter/table.demo") as unknown as Promise<DemoModule>,
  "alert": () => import("@registry/ui/perimeter/alert.demo") as unknown as Promise<DemoModule>,
  "alert-dialog": () => import("@registry/ui/perimeter/alert-dialog.demo") as unknown as Promise<DemoModule>,
  "dialog": () => import("@registry/ui/perimeter/dialog.demo") as unknown as Promise<DemoModule>,
  "drawer": () => import("@registry/ui/perimeter/drawer.demo") as unknown as Promise<DemoModule>,
  "hover-card": () => import("@registry/ui/perimeter/hover-card.demo") as unknown as Promise<DemoModule>,
  "popover": () => import("@registry/ui/perimeter/popover.demo") as unknown as Promise<DemoModule>,
  "sheet": () => import("@registry/ui/perimeter/sheet.demo") as unknown as Promise<DemoModule>,
  "sonner": () => import("@registry/ui/perimeter/sonner.demo") as unknown as Promise<DemoModule>,
  "tooltip": () => import("@registry/ui/perimeter/tooltip.demo") as unknown as Promise<DemoModule>,
  "calendar": () => import("@registry/ui/perimeter/calendar.demo") as unknown as Promise<DemoModule>,
  "checkbox": () => import("@registry/ui/perimeter/checkbox.demo") as unknown as Promise<DemoModule>,
  "combobox": () => import("@registry/ui/perimeter/combobox.demo") as unknown as Promise<DemoModule>,
  "field": () => import("@registry/ui/perimeter/field.demo") as unknown as Promise<DemoModule>,
  "input": () => import("@registry/ui/perimeter/input.demo") as unknown as Promise<DemoModule>,
  "input-group": () => import("@registry/ui/perimeter/input-group.demo") as unknown as Promise<DemoModule>,
  "input-otp": () => import("@registry/ui/perimeter/input-otp.demo") as unknown as Promise<DemoModule>,
  "label": () => import("@registry/ui/perimeter/label.demo") as unknown as Promise<DemoModule>,
  "native-select": () => import("@registry/ui/perimeter/native-select.demo") as unknown as Promise<DemoModule>,
  "radio-group": () => import("@registry/ui/perimeter/radio-group.demo") as unknown as Promise<DemoModule>,
  "select": () => import("@registry/ui/perimeter/select.demo") as unknown as Promise<DemoModule>,
  "slider": () => import("@registry/ui/perimeter/slider.demo") as unknown as Promise<DemoModule>,
  "switch": () => import("@registry/ui/perimeter/switch.demo") as unknown as Promise<DemoModule>,
  "textarea": () => import("@registry/ui/perimeter/textarea.demo") as unknown as Promise<DemoModule>,
  "accordion": () => import("@registry/ui/perimeter/accordion.demo") as unknown as Promise<DemoModule>,
  "aspect-ratio": () => import("@registry/ui/perimeter/aspect-ratio.demo") as unknown as Promise<DemoModule>,
  "collapsible": () => import("@registry/ui/perimeter/collapsible.demo") as unknown as Promise<DemoModule>,
  "direction": () => import("@registry/ui/perimeter/direction.demo") as unknown as Promise<DemoModule>,
  "resizable": () => import("@registry/ui/perimeter/resizable.demo") as unknown as Promise<DemoModule>,
  "scroll-area": () => import("@registry/ui/perimeter/scroll-area.demo") as unknown as Promise<DemoModule>,
  "separator": () => import("@registry/ui/perimeter/separator.demo") as unknown as Promise<DemoModule>,
  "item": () => import("@registry/ui/perimeter/item.demo") as unknown as Promise<DemoModule>,
  "kbd": () => import("@registry/ui/perimeter/kbd.demo") as unknown as Promise<DemoModule>,
  "spinner": () => import("@registry/ui/perimeter/spinner.demo") as unknown as Promise<DemoModule>,
  "breadcrumb": () => import("@registry/ui/perimeter/breadcrumb.demo") as unknown as Promise<DemoModule>,
  "command": () => import("@registry/ui/perimeter/command.demo") as unknown as Promise<DemoModule>,
  "navigation-menu": () => import("@registry/ui/perimeter/navigation-menu.demo") as unknown as Promise<DemoModule>,
  "pagination": () => import("@registry/ui/perimeter/pagination.demo") as unknown as Promise<DemoModule>,
  "sidebar": () => import("@registry/ui/perimeter/sidebar.demo") as unknown as Promise<DemoModule>,
  "tabs": () => import("@registry/ui/perimeter/tabs.demo") as unknown as Promise<DemoModule>,
};
